/**
 * Template Corpus Smoke Tests
 *
 * For each fixture JSON file generated by `npm run refresh-template-fixtures`,
 * renders FormProvider with the template's resolved Field[] and asserts the
 * component mounts without throwing.
 *
 * If no fixture files are found, the test suite skips with a reminder to run
 * `npm run refresh-template-fixtures` first.
 *
 * See AGENTS.md §Corpus Testing for details.
 */

import { describe, it, expect } from 'vitest';
import { render, screen } from '../../test-utils';
import { MemoryRouter } from 'react-router';
import { FormProvider } from '../../../src/components/SukohForm/FormProvider';
import type { Field } from '@quiqr/types';

// ---------------------------------------------------------------------------
// Fixture loading via import.meta.glob
// ---------------------------------------------------------------------------

interface TemplateFixture {
  templateName: string;
  key: string;
  kind: 'collection' | 'single';
  fields: Field[];
  initialValues: Record<string, unknown>;
}

// Load all fixture JSON files eagerly at test collection time.
// Vitest supports import.meta.glob natively (same as Vite).
const fixtureModules = import.meta.glob<{ default: TemplateFixture }>(
  '../../fixtures/templates/**/*.json',
  { eager: true }
);

const fixtures: TemplateFixture[] = Object.values(fixtureModules).map((m) => m.default);

// ---------------------------------------------------------------------------
// Test metadata
// ---------------------------------------------------------------------------

const testMeta = {
  siteKey: 'corpus-test',
  workspaceKey: 'main',
  collectionKey: '',
  collectionItemKey: '',
  prompt_templates: [],
  pageUrl: '',
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Template Corpus Smoke Tests', () => {
  if (fixtures.length === 0) {
    it.skip(
      'No fixture files found — run `npm run refresh-template-fixtures` to generate them',
      () => {
        // intentional no-op
      }
    );
  } else {
    for (const fixture of fixtures) {
      it(`${fixture.templateName} / ${fixture.kind}: ${fixture.key} — renders without crashing`, () => {
        render(
          <MemoryRouter initialEntries={['/']}>
            <FormProvider
              fields={fixture.fields}
              initialValues={fixture.initialValues}
              meta={testMeta}
              onSave={async () => {}}
            >
              <div data-testid="smoke-mounted">mounted</div>
            </FormProvider>
          </MemoryRouter>
        );

        expect(screen.getByTestId('smoke-mounted')).toBeInTheDocument();
      });
    }
  }
});
